### ISSUE TITLE
Compressed sound

### ISSUE THREAD

**Issue by donpeterd** [Groggy/race-control-tv#1]
So fantastic you created this app we ALL have been waiting for!
Hopefully days of streaming over iPhone, with 10-15 breakdowns through the race are over! THANK YOU!!

But the sound is sadly SUPER compressed. That shimmer where your struggle to compute what Brundle are saying. Like the really bad YouTube clips, where you get that feeling of having a chainsaw right next to your ears. 
That would be over the top  awesome, if that could be fixed!!

You can clearly tell, the sound stream is A LOT richer and cleaner, when streaming from iPhone to the AirScreen app on the shield. 
Picture frame rate and resolution SEEMS to run smoother too. 

I’m watching on a big screen, and text has that edge glow, like upscaled and post process sharpened material has, in your app. 

I don’t know it helps you, but streaming Netflix of a MacBook Pro via HDMI looks horrible! Through the Shield Netflix app it looks almost like uncompressed 1080P material. Almost...
So there ARE two streams to source from - perhaps the same goes for F1TV!?

Sincerely hope you will look into those problems buddy.

**Comment by Groggy** [comment]
I have not encounter any sound issue. In fact, F1 TV does provide multiple video streams with different qualities and the app will automatically use the highest quality video stream if your connection is good enough. F1 TV also provides multiple audio streams but with different languages and they have all the same sound quality.

I will not look into your issue, because I'm no longer using this app as I'm not susbscribed to F1 TV anymore.
